[
        {
          chapter: 13,
          sloka: 19,
          devanagari: "इति क्षेत्रं तथा ज्ञानं ज्ञेयं चोक्तं समासतः ।\nमद्भक्त एतद्विज्ञाय मद्भावायोपपद्यते ॥१९॥",
          transliteration: "iti kṣetraṁ tathā jñānaṁ jñeyaṁ coktaṁ samāsataḥ |\nmad-bhakta etad vijñāya mad-bhāvāyopapadyate ||19||",
          words: [
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "क्षेत्रम्", transliteration: "kṣetram", meaning: "the field (body)" },
            { word: "तथा", transliteration: "tathā", meaning: "also" },
            { word: "ज्ञानम्", transliteration: "jñānam", meaning: "knowledge" },
            { word: "ज्ञेयम्", transliteration: "jñeyam", meaning: "the knowable" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "उक्तम्", transliteration: "uktam", meaning: "has been described" },
            { word: "समासतः", transliteration: "samāsataḥ", meaning: "in summary" },
            { word: "मद्भक्तः", transliteration: "mad-bhaktaḥ", meaning: "My devotee" },
            { word: "एतत्", transliteration: "etat", meaning: "this" },
            { word: "विज्ञाय", transliteration: "vijñāya", meaning: "having understood" },
            { word: "मद्भावाय", transliteration: "mad-bhāvāya", meaning: "to My nature/state" },
            { word: "उपपद्यते", transliteration: "upapadyate", meaning: "attains" }
          ],
          translation: "Thus the Field, Knowledge, and the Knowable have been briefly described. My devotee, understanding all this, becomes worthy of attaining My nature.",
          modernInterpretation: "Krishna just hit the RECAP button. He says, 'Look, I have told you three things in summary — the KSHETRA (what the field is), JNANA (what true knowledge looks like), and JNEYA (what is worth knowing). Now — my DEVOTEE, the one who actually GETS this, reaches MY state.' Simple as that.\n\nThis is like the end of a Netflix episode recap — 'Previously on Bhagavad Gita: We covered the body, the qualities of a wise person, and the ultimate reality. NOW, the real plot begins.' And notice the word MAD-BHAKTA — MY devotee. Not just anyone who reads this casually. Not someone who bookmarks this and says 'I will read later.' The one who is genuinely DEVOTED, who takes this knowledge and INTERNALISES it — that person attains MAD-BHAVA, Krishna's own nature.\n\nThis is the ultimate university promise. 'Complete this course with sincerity and you will not just get a DEGREE — you will become a PROFESSOR.' Krishna is not offering you a certificate. He is offering you His own STATE of being. From student to the level of the teacher. From the drop to the ocean. No other guru makes this promise. No other teacher says 'Study my subject and you will BECOME me.' Only the Supreme can offer that. And He is offering it RIGHT NOW."
        },
        {
          chapter: 13,
          sloka: 20,
          devanagari: "प्रकृतिं पुरुषं चैव विद्ध्यनादी उभावपि ।\nविकारांश्च गुणांश्चैव विद्धि प्रकृतिसम्भवान् ॥२०॥",
          transliteration: "prakṛtiṁ puruṣaṁ caiva viddhy anādī ubhāv api |\nvikārāṁś ca guṇāṁś caiva viddhi prakṛti-sambhavān ||20||",
          words: [
            { word: "प्रकृतिम्", transliteration: "prakṛtim", meaning: "material nature" },
            { word: "पुरुषम्", transliteration: "puruṣam", meaning: "the conscious self/soul" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "एव", transliteration: "eva", meaning: "indeed" },
            { word: "विद्धि", transliteration: "viddhi", meaning: "know" },
            { word: "अनादी", transliteration: "anādī", meaning: "beginningless" },
            { word: "उभौ", transliteration: "ubhau", meaning: "both" },
            { word: "अपि", transliteration: "api", meaning: "also" },
            { word: "विकारान्", transliteration: "vikārān", meaning: "modifications/transformations" },
            { word: "गुणान्", transliteration: "guṇān", meaning: "qualities" },
            { word: "प्रकृतिसम्भवान्", transliteration: "prakṛti-sambhavān", meaning: "born of material nature" }
          ],
          translation: "Know that both Prakriti (material nature) and Purusha (the conscious self) are beginningless. And know that all modifications and qualities are born of Prakriti.",
          modernInterpretation: "This is Krishna dropping a MASSIVE philosophical bomb. He says both Prakriti (nature) and Purusha (consciousness) are BEGINNINGLESS. Neither was created — they have always existed. This is not some Big Bang theory where everything started from nothing. Krishna says the raw material AND the observer have ALWAYS been there. No start date. No 'founded in 2015.' No incorporation certificate.\n\nNow here is the key insight — all the CHANGES, all the drama, all the transformations you see in the world? Those come from PRAKRITI, not from Purusha. Your mood swings? Prakriti. Your body aging? Prakriti. The stock market crashing? Prakriti doing Prakriti things. The SOUL does not change — it just WATCHES. Think of it like Netflix. The screen does not become sad when a sad movie plays. The screen does not age when the character ages. The screen is just THERE — unchanged, unaffected. YOU are the screen. The movie is Prakriti.\n\nSo next time life throws chaos at you — job loss, breakup, that uncle asking 'beta, shaadi kab?' — remember: that is just Prakriti's MODIFICATIONS playing out. The real YOU has not moved an inch."
        },
        {
          chapter: 13,
          sloka: 21,
          devanagari: "कार्यकारणकर्तृत्वे हेतुः प्रकृतिरुच्यते ।\nपुरुषः सुखदुःखानां भोक्तृत्वे हेतुरुच्यते ॥२१॥",
          transliteration: "kārya-kāraṇa-kartṛtve hetuḥ prakṛtir ucyate |\npuruṣaḥ sukha-duḥkhānāṁ bhoktṛtve hetur ucyate ||21||",
          words: [
            { word: "कार्य", transliteration: "kārya", meaning: "effect/body" },
            { word: "कारण", transliteration: "kāraṇa", meaning: "cause/instruments" },
            { word: "कर्तृत्वे", transliteration: "kartṛtve", meaning: "in the matter of agency/doership" },
            { word: "हेतुः", transliteration: "hetuḥ", meaning: "the cause/reason" },
            { word: "प्रकृतिः", transliteration: "prakṛtiḥ", meaning: "material nature" },
            { word: "उच्यते", transliteration: "ucyate", meaning: "is said" },
            { word: "पुरुषः", transliteration: "puruṣaḥ", meaning: "the conscious self" },
            { word: "सुखदुःखानाम्", transliteration: "sukha-duḥkhānām", meaning: "of pleasures and pains" },
            { word: "भोक्तृत्वे", transliteration: "bhoktṛtve", meaning: "in the matter of experiencing" },
            { word: "हेतुः", transliteration: "hetuḥ", meaning: "the cause" }
          ],
          translation: "In the creation of effects and instruments of action, Prakriti is said to be the cause. In the experience of pleasure and pain, Purusha is said to be the cause.",
          modernInterpretation: "Krishna is drawing the CLEANEST division of labour in the universe. Prakriti is the DOER — she builds the body, creates the senses, manufactures the organs, runs the hormones, does all the ENGINEERING. She is the CTO. But Purusha — the soul — is the EXPERIENCER. He is the one who FEELS the output of all that engineering.\n\nThink of it like this. Your phone (Prakriti) generates notifications, plays videos, shows Instagram reels. But YOU (Purusha) are the one who feels happy seeing a meme or angry reading a tweet. The phone does not feel anything. And technically, you should not either — but you DO, because you have IDENTIFIED with the phone. You think you ARE the phone.\n\nThis is exactly how suffering works. The body gets a headache — Prakriti's doing. But the SOUL says 'I have a headache' — that is the soul taking ownership of something that is not even its department. It is like the CEO crying because the printer jammed. Bhai, that is an INFRASTRUCTURE problem, not a YOU problem. But because Purusha sits inside Prakriti and identifies with it, every printer jam feels like a personal crisis. THAT is the trap. And understanding this division? That is the beginning of FREEDOM."
        },
        {
          chapter: 13,
          sloka: 22,
          devanagari: "पुरुषः प्रकृतिस्थो हि भुङ्क्ते प्रकृतिजान्गुणान् ।\nकारणं गुणसङ्गोऽस्य सदसद्योनिजन्मसु ॥२२॥",
          transliteration: "puruṣaḥ prakṛti-stho hi bhuṅkte prakṛti-jān guṇān |\nkāraṇaṁ guṇa-saṅgo'sya sad-asad-yoni-janmasu ||22||",
          words: [
            { word: "पुरुषः", transliteration: "puruṣaḥ", meaning: "the conscious self" },
            { word: "प्रकृतिस्थः", transliteration: "prakṛti-sthaḥ", meaning: "situated in material nature" },
            { word: "हि", transliteration: "hi", meaning: "indeed" },
            { word: "भुङ्क्ते", transliteration: "bhuṅkte", meaning: "enjoys/experiences" },
            { word: "प्रकृतिजान्", transliteration: "prakṛti-jān", meaning: "born of material nature" },
            { word: "गुणान्", transliteration: "guṇān", meaning: "the qualities/gunas" },
            { word: "कारणम्", transliteration: "kāraṇam", meaning: "the cause" },
            { word: "गुणसङ्गः", transliteration: "guṇa-saṅgaḥ", meaning: "attachment to the gunas" },
            { word: "अस्य", transliteration: "asya", meaning: "of this (soul)" },
            { word: "सदसद्योनिजन्मसु", transliteration: "sad-asad-yoni-janmasu", meaning: "in births in good and evil wombs" }
          ],
          translation: "The Purusha, seated in Prakriti, experiences the qualities born of Prakriti. Attachment to the gunas is the cause of its birth in good and evil wombs.",
          modernInterpretation: "HERE is the verse that explains the ENTIRE cycle of birth and death in two lines. Why does the soul keep taking births? GUNA-SANGA — attachment to the gunas. That is it. Full stop. Not because God is punishing you. Not because of some cosmic lottery. But because YOU got ATTACHED to the flavours of Prakriti.\n\nImagine you walk into a mall just to use the washroom. But then you see a sale — 70% off. You go in 'just to look.' Three hours later you are carrying six bags and your credit card is weeping. You did not PLAN to shop. But you got ATTACHED to the experience. That is exactly what happens to the soul. It enters Prakriti temporarily, gets a taste of pleasure and pain, and goes 'Oh, this is INTERESTING' — and gets hooked.\n\nAnd depending on WHICH gunas you get attached to, you get different births. Attached to sattva? You get born in a good family, good circumstances — maybe you are that kid who tops boards without studying. Attached to rajas and tamas? You end up in tougher circumstances. It is not punishment — it is PHYSICS. You are attracted to certain frequencies, so you get tuned into those channels. DETACH from the gunas, and the cycle STOPS. Simple in theory. A lifetime's work in practice."
        },
        {
          chapter: 13,
          sloka: 23,
          devanagari: "उपद्रष्टानुमन्ता च भर्ता भोक्ता महेश्वरः ।\nपरमात्मेति चाप्युक्तो देहेऽस्मिन्पुरुषः परः ॥२३॥",
          transliteration: "upadraṣṭānumantā ca bhartā bhoktā maheśvaraḥ |\nparamātmeti cāpy ukto dehe'smin puruṣaḥ paraḥ ||23||",
          words: [
            { word: "उपद्रष्टा", transliteration: "upadraṣṭā", meaning: "the witness/overseer" },
            { word: "अनुमन्ता", transliteration: "anumantā", meaning: "the permitter" },
            { word: "भर्ता", transliteration: "bhartā", meaning: "the sustainer" },
            { word: "भोक्ता", transliteration: "bhoktā", meaning: "the experiencer" },
            { word: "महेश्वरः", transliteration: "maheśvaraḥ", meaning: "the Supreme Lord" },
            { word: "परमात्मा", transliteration: "paramātmā", meaning: "the Supreme Self" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "अपि", transliteration: "api", meaning: "also" },
            { word: "उक्तः", transliteration: "uktaḥ", meaning: "is said/called" },
            { word: "देहे", transliteration: "dehe", meaning: "in the body" },
            { word: "अस्मिन्", transliteration: "asmin", meaning: "in this" },
            { word: "पुरुषः", transliteration: "puruṣaḥ", meaning: "the person/self" },
            { word: "परः", transliteration: "paraḥ", meaning: "the Supreme" }
          ],
          translation: "The Supreme Self in this body is also called the Witness, the Permitter, the Sustainer, the Experiencer, the Great Lord, and the Paramatma (Supreme Soul).",
          modernInterpretation: "Krishna just listed FIVE job titles for the Supreme Soul sitting inside your body. Upadrashta — the WITNESS who watches everything silently like that one friend in the group who sees all the drama but says nothing. Anumanta — the PERMITTER who allows things to happen, like a parent letting a toddler make mistakes so they learn. Bharta — the SUSTAINER who keeps the whole show running, like that one person in every Indian family who quietly pays all the bills. Bhokta — the EXPERIENCER. And Maheshvara — the SUPREME LORD.\n\nSo let me get this straight — God is not sitting in some far-off heaven judging you from a distance. He is RIGHT THERE inside you, closer than your own heartbeat, watching, permitting, sustaining. He is not your Swiggy delivery guy who comes and goes. He is your ROOMMATE. He is with you 24/7.\n\nAnd He is called PARAMATMA — the Supreme Self — different from your individual atma. Think of it like this: your atma is like a single Wi-Fi device, and the Paramatma is the ROUTER. Every device has its own identity, but they are all connected to and sustained by the same source. You are never truly ALONE. The Paramatma is always watching, always supporting, always there. That is not surveillance — that is LOVE."
        },
        {
          chapter: 13,
          sloka: 24,
          devanagari: "य एवं वेत्ति पुरुषं प्रकृतिं च गुणैः सह ।\nसर्वथा वर्तमानोऽपि न स भूयोऽभिजायते ॥२४॥",
          transliteration: "ya evaṁ vetti puruṣaṁ prakṛtiṁ ca guṇaiḥ saha |\nsarvathā vartamāno'pi na sa bhūyo'bhijāyate ||24||",
          words: [
            { word: "यः", transliteration: "yaḥ", meaning: "he who" },
            { word: "एवम्", transliteration: "evam", meaning: "thus" },
            { word: "वेत्ति", transliteration: "vetti", meaning: "knows" },
            { word: "पुरुषम्", transliteration: "puruṣam", meaning: "the conscious self" },
            { word: "प्रकृतिम्", transliteration: "prakṛtim", meaning: "material nature" },
            { word: "गुणैः", transliteration: "guṇaiḥ", meaning: "with the gunas" },
            { word: "सह", transliteration: "saha", meaning: "together" },
            { word: "सर्वथा", transliteration: "sarvathā", meaning: "in every way" },
            { word: "वर्तमानः", transliteration: "vartamānaḥ", meaning: "existing/living" },
            { word: "अपि", transliteration: "api", meaning: "even" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "सः", transliteration: "saḥ", meaning: "he" },
            { word: "भूयः", transliteration: "bhūyaḥ", meaning: "again" },
            { word: "अभिजायते", transliteration: "abhijāyate", meaning: "is born" }
          ],
          translation: "He who thus knows the Purusha and Prakriti along with the gunas, regardless of his present condition, is not born again.",
          modernInterpretation: "This is the ULTIMATE promise. Krishna says if you truly understand three things — Purusha (the soul), Prakriti (material nature), and the three gunas (sattva, rajas, tamas) — you are DONE. No more rebirths. No more coming back to deal with Mumbai traffic, board exams, and relatives asking about your salary. You are FREE.\n\nAnd the beautiful part is — 'sarvathā vartamānaḥ api' — REGARDLESS of your current situation. You could be a CEO or a chai-wallah. You could be in an ashram or in Andheri West sharing a 1BHK with four roommates. Your current CIRCUMSTANCES do not matter. What matters is your UNDERSTANDING.\n\nThis is so liberating. Krishna is not saying you need to renounce everything, go to the Himalayas, grow a beard, and eat roots. He is saying you can be RIGHT WHERE YOU ARE — stuck in a 9-to-5, commuting in a packed metro, dealing with your in-laws — and if you TRULY understand the Purusha-Prakriti-Guna framework, you are liberated. It is not about changing your LOCATION. It is about changing your UNDERSTANDING. The jail is not the body, the jail is IGNORANCE. And knowledge is the key that opens EVERY lock."
        },
        {
          chapter: 13,
          sloka: 25,
          devanagari: "ध्यानेनात्मनि पश्यन्ति केचिदात्मानमात्मना ।\nअन्ये साङ्ख्येन योगेन कर्मयोगेन चापरे ॥२५॥",
          transliteration: "dhyānenātmani paśyanti kecid ātmānam ātmanā |\nanye sāṅkhyena yogena karma-yogena cāpare ||25||",
          words: [
            { word: "ध्यानेन", transliteration: "dhyānena", meaning: "by meditation" },
            { word: "आत्मनि", transliteration: "ātmani", meaning: "in the self" },
            { word: "पश्यन्ति", transliteration: "paśyanti", meaning: "see/perceive" },
            { word: "केचित्", transliteration: "kecit", meaning: "some" },
            { word: "आत्मानम्", transliteration: "ātmānam", meaning: "the Self" },
            { word: "आत्मना", transliteration: "ātmanā", meaning: "by the self/mind" },
            { word: "अन्ये", transliteration: "anye", meaning: "others" },
            { word: "साङ्ख्येन", transliteration: "sāṅkhyena", meaning: "by the path of knowledge (Sankhya)" },
            { word: "योगेन", transliteration: "yogena", meaning: "by yoga" },
            { word: "कर्मयोगेन", transliteration: "karma-yogena", meaning: "by the yoga of selfless action" },
            { word: "अपरे", transliteration: "apare", meaning: "yet others" }
          ],
          translation: "Some perceive the Self in the self by meditation, others by the path of knowledge (Sankhya), and yet others by the path of selfless action (Karma Yoga).",
          modernInterpretation: "THIS verse is why the Gita is the most INCLUSIVE spiritual text ever written. Krishna is saying there is NOT just one way to find God. Some people meditate — they sit quietly, go inward, and find the truth through DHYANA. Some people use KNOWLEDGE — they read, analyse, debate, use their intellect like a laser beam to cut through illusion. That is Sankhya Yoga. And some people? They just DO WORK — selflessly, without attachment — and through that karma, they find the divine.\n\nThink about it. In a class of 60 students, does everyone learn the same way? Some are visual learners. Some learn by doing. Some need to hear it explained. A GOOD teacher does not force one method. And Krishna is the GREATEST teacher. He says, 'Pick your path. Whatever works for YOUR nature.'\n\nThis is why Hinduism never had religious wars about methodology. You want to meditate? Great. You want to study scriptures? Fantastic. You want to serve the poor and call that your worship? EQUALLY valid. It is like reaching Mumbai — you can take a flight, a train, or drive. You can even WALK if you are that hardcore. The destination is the same. Krishna does not care about your MODE of transport. He cares that you are MOVING. So stop judging the meditator if you are a karma yogi, and stop looking down on the worker if you are a jnani. Everyone has their route. RESPECT it."
        },
        {
          chapter: 13,
          sloka: 26,
          devanagari: "अन्ये त्वेवमजानन्तः श्रुत्वान्येभ्य उपासते ।\nतेऽपि चातितरन्त्येव मृत्युं श्रुतिपरायणाः ॥२६॥",
          transliteration: "anye tv evam ajānantaḥ śrutvānyebhya upāsate |\nte'pi cātitaranty eva mṛtyuṁ śruti-parāyaṇāḥ ||26||",
          words: [
            { word: "अन्ये", transliteration: "anye", meaning: "others" },
            { word: "तु", transliteration: "tu", meaning: "but" },
            { word: "एवम्", transliteration: "evam", meaning: "thus" },
            { word: "अजानन्तः", transliteration: "ajānantaḥ", meaning: "not knowing" },
            { word: "श्रुत्वा", transliteration: "śrutvā", meaning: "having heard" },
            { word: "अन्येभ्यः", transliteration: "anyebhyaḥ", meaning: "from others" },
            { word: "उपासते", transliteration: "upāsate", meaning: "worship/practise" },
            { word: "ते", transliteration: "te", meaning: "they" },
            { word: "अपि", transliteration: "api", meaning: "also" },
            { word: "अतितरन्ति", transliteration: "atitaranti", meaning: "cross beyond" },
            { word: "एव", transliteration: "eva", meaning: "certainly" },
            { word: "मृत्युम्", transliteration: "mṛtyum", meaning: "death" },
            { word: "श्रुतिपरायणाः", transliteration: "śruti-parāyaṇāḥ", meaning: "devoted to hearing" }
          ],
          translation: "Yet others, not knowing these paths, worship by hearing from others. They too cross beyond death, being devoted to what they have heard.",
          modernInterpretation: "This verse is Krishna's SAFETY NET for everyone who thinks 'But I am not a yogi, I am not a scholar, I do not even know how to meditate properly.' Krishna says EVEN if you do not know any of the three paths — meditation, knowledge, or karma yoga — if you simply LISTEN to someone who knows and follow their guidance with faith, YOU ALSO cross beyond death.\n\nThis is HUGE. This means your grandmother who cannot read Sanskrit but listens to Bhagavat Katha with full devotion on the TV — she is covered. That auto driver who has a small Gita in his dashboard and listens to pravachans on YouTube while waiting for passengers — he is covered. You do not need a PhD in Vedanta. You need EARS and FAITH.\n\nShruti-parayana — devoted to LISTENING. In our culture, SHRAVANAM (listening) has always been the first step of learning. Before you read, before you practise, you LISTEN. That is why satsang exists. That is why pravachans exist. That is why your dadi keeps forcing you to sit during the evening aarti — because just HEARING sacred words, even without fully understanding them, creates TRANSFORMATION. It is like music. You do not need to understand the raaga to be moved by it. The vibration does the work. Just SHOW UP and LISTEN. Krishna will handle the rest."
        },
        {
          chapter: 13,
          sloka: 27,
          devanagari: "यावत्सञ्जायते किञ्चित्सत्त्वं स्थावरजङ्गमम् ।\nक्षेत्रक्षेत्रज्ञसंयोगात्तद्विद्धि भरतर्षभ ॥२७॥",
          transliteration: "yāvat sañjāyate kiñcit sattvaṁ sthāvara-jaṅgamam |\nkṣetra-kṣetrajña-saṁyogāt tad viddhi bharatarṣabha ||27||",
          words: [
            { word: "यावत्", transliteration: "yāvat", meaning: "whatever" },
            { word: "सञ्जायते", transliteration: "sañjāyate", meaning: "is born/comes into being" },
            { word: "किञ्चित्", transliteration: "kiñcit", meaning: "anything" },
            { word: "सत्त्वम्", transliteration: "sattvam", meaning: "being/entity" },
            { word: "स्थावर", transliteration: "sthāvara", meaning: "stationary/immovable" },
            { word: "जङ्गमम्", transliteration: "jaṅgamam", meaning: "moving" },
            { word: "क्षेत्र", transliteration: "kṣetra", meaning: "the field (body)" },
            { word: "क्षेत्रज्ञ", transliteration: "kṣetrajña", meaning: "the knower of the field (soul)" },
            { word: "संयोगात्", transliteration: "saṁyogāt", meaning: "from the union/combination" },
            { word: "तत्", transliteration: "tat", meaning: "that" },
            { word: "विद्धि", transliteration: "viddhi", meaning: "know" },
            { word: "भरतर्षभ", transliteration: "bharatarṣabha", meaning: "O best of the Bharatas" }
          ],
          translation: "Whatever being is born, whether moving or unmoving, know that it arises from the union of the Field (Kshetra) and the Knower of the Field (Kshetrajna), O best of the Bharatas.",
          modernInterpretation: "Krishna just gave you the FORMULA for all of creation. Every single thing that exists — from the banyan tree standing still for 500 years to the sparrow flying past your window to your neighbour's annoying dog that barks at 3 AM — ALL of it exists because of the UNION of Kshetra (the field/matter) and Kshetrajna (the knower/consciousness). Body plus soul. Hardware plus software. Without the body, the soul has no vehicle. Without the soul, the body is just a lump of organic matter.\n\nThis is literally the recipe for ALL life. Take some Prakriti (matter), add some consciousness (Purusha), mix well — boom, you have a living being. A plant? Kshetra plus Kshetrajna. An ant? Same formula. A whale? Same formula. Elon Musk? SAME formula. The ingredients are identical — what differs is the PROPORTION and complexity of the field.\n\nThis should make you see EVERY living being differently. That stray dog on the road? Kshetra-Kshetrajna samyoga. That tree you walk past without noticing? Same divine combination. The cockroach you are about to smash with a chappal? Consciousness is INSIDE that too. This is not tree-hugging hippie philosophy. This is the PHYSICS of existence as described by the Supreme Being Himself."
        },
        {
          chapter: 13,
          sloka: 28,
          devanagari: "समं सर्वेषु भूतेषु तिष्ठन्तं परमेश्वरम् ।\nविनश्यत्स्वविनश्यन्तं यः पश्यति स पश्यति ॥२८॥",
          transliteration: "samaṁ sarveṣu bhūteṣu tiṣṭhantaṁ parameśvaram |\nvinaśyatsv avinaśyantaṁ yaḥ paśyati sa paśyati ||28||",
          words: [
            { word: "समम्", transliteration: "samam", meaning: "equally" },
            { word: "सर्वेषु", transliteration: "sarveṣu", meaning: "in all" },
            { word: "भूतेषु", transliteration: "bhūteṣu", meaning: "beings" },
            { word: "तिष्ठन्तम्", transliteration: "tiṣṭhantam", meaning: "dwelling/existing" },
            { word: "परमेश्वरम्", transliteration: "parameśvaram", meaning: "the Supreme Lord" },
            { word: "विनश्यत्सु", transliteration: "vinaśyatsu", meaning: "in the perishable" },
            { word: "अविनश्यन्तम्", transliteration: "avinaśyantam", meaning: "the imperishable" },
            { word: "यः", transliteration: "yaḥ", meaning: "he who" },
            { word: "पश्यति", transliteration: "paśyati", meaning: "sees" },
            { word: "सः", transliteration: "saḥ", meaning: "he" },
            { word: "पश्यति", transliteration: "paśyati", meaning: "truly sees" }
          ],
          translation: "He who sees the Supreme Lord dwelling equally in all beings — the imperishable within the perishable — he truly sees.",
          modernInterpretation: "YAH PASHYATI SA PASHYATI. He who SEES, truly SEES. This might be the most powerful line in all of Chapter 13. Krishna is redefining what it means to have VISION. Most of us think seeing means using our eyes. But Krishna says real seeing is perceiving the IMPERISHABLE Supreme Lord dwelling EQUALLY in ALL perishable beings.\n\nEQUALLY. Not more in a Brahmin, less in a Shudra. Not more in a human, less in an animal. Not more in a rich person, less in a beggar. EQUALLY. Same Wi-Fi signal strength everywhere. Same divine presence in the IAS officer and the watchman. Same Paramatma in the peacock and the pigeon.\n\nAnd here is the mind-bending part — this imperishable Lord exists in things that ARE perishing. The body is dying every second — cells are replacing, aging is happening, entropy is doing its thing. But INSIDE this constantly decaying vehicle, something INDESTRUCTIBLE sits calmly. It is like finding a diamond inside a mud pot. The pot will break, but the diamond does not care.\n\nSo the next time you judge someone by their body, their clothes, their caste, their Instagram followers — remember: you are judging the MUD POT. The diamond inside is IDENTICAL in everyone. The one who sees THAT — sa pashyati — THAT person truly sees."
        },
        {
          chapter: 13,
          sloka: 29,
          devanagari: "समं पश्यन्हि सर्वत्र समवस्थितमीश्वरम् ।\nन हिनस्त्यात्मनात्मानं ततो याति परां गतिम् ॥२९॥",
          transliteration: "samaṁ paśyan hi sarvatra samavasthitam īśvaram |\nna hinasty ātmanātmānaṁ tato yāti parāṁ gatim ||29||",
          words: [
            { word: "समम्", transliteration: "samam", meaning: "equally" },
            { word: "पश्यन्", transliteration: "paśyan", meaning: "seeing" },
            { word: "हि", transliteration: "hi", meaning: "indeed" },
            { word: "सर्वत्र", transliteration: "sarvatra", meaning: "everywhere" },
            { word: "समवस्थितम्", transliteration: "samavasthitam", meaning: "equally situated" },
            { word: "ईश्वरम्", transliteration: "īśvaram", meaning: "the Lord" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "हिनस्ति", transliteration: "hinasti", meaning: "destroys/degrades" },
            { word: "आत्मना", transliteration: "ātmanā", meaning: "by the self" },
            { word: "आत्मानम्", transliteration: "ātmānam", meaning: "the self" },
            { word: "ततः", transliteration: "tataḥ", meaning: "then/thereby" },
            { word: "याति", transliteration: "yāti", meaning: "reaches/attains" },
            { word: "पराम्", transliteration: "parām", meaning: "the supreme" },
            { word: "गतिम्", transliteration: "gatim", meaning: "destination/goal" }
          ],
          translation: "Seeing the Lord equally present everywhere, one does not degrade oneself by oneself, and thus attains the supreme goal.",
          modernInterpretation: "This is the PRACTICAL benefit of the vision described in the previous verse. When you see God equally in everyone, what happens? You stop DESTROYING yourself. 'Na hinasti atmanam atmana' — you do not degrade yourself BY yourself.\n\nThink about it — how do we destroy ourselves? Through hatred, jealousy, cruelty, arrogance. And WHERE do these come from? From seeing DIFFERENCES. 'He is better than me' — jealousy. 'She is lower than me' — arrogance. 'They are different from me' — hatred. ALL self-destruction comes from seeing INEQUALITY where there is actually EQUALITY.\n\nBut the moment you see Ishvara equally in the beggar and the billionaire, in the crow and the peacock, in your friend and your enemy — ALL those toxic emotions lose their FUEL. You cannot hate someone when you see God in them. You cannot be arrogant when you see the same God in everyone, including those you consider 'below' you.\n\nAnd the result? PARAM GATIM — the supreme destination. Not some average moksha. The HIGHEST goal. The VIP lounge of spiritual achievement. And the ticket? Not expensive rituals or extreme austerity. Just EQUAL VISION. See God everywhere. That is it. The hardest simple thing you will ever do."
        },
        {
          chapter: 13,
          sloka: 30,
          devanagari: "प्रकृत्यैव च कर्माणि क्रियमाणानि सर्वशः ।\nयः पश्यति तथात्मानमकर्तारं स पश्यति ॥३०॥",
          transliteration: "prakṛtyaiva ca karmāṇi kriyamāṇāni sarvaśaḥ |\nyaḥ paśyati tathātmānam akartāraṁ sa paśyati ||30||",
          words: [
            { word: "प्रकृत्या", transliteration: "prakṛtyā", meaning: "by material nature" },
            { word: "एव", transliteration: "eva", meaning: "alone/only" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "कर्माणि", transliteration: "karmāṇi", meaning: "actions" },
            { word: "क्रियमाणानि", transliteration: "kriyamāṇāni", meaning: "being performed" },
            { word: "सर्वशः", transliteration: "sarvaśaḥ", meaning: "in all respects" },
            { word: "यः", transliteration: "yaḥ", meaning: "he who" },
            { word: "पश्यति", transliteration: "paśyati", meaning: "sees" },
            { word: "तथा", transliteration: "tathā", meaning: "also" },
            { word: "आत्मानम्", transliteration: "ātmānam", meaning: "the self" },
            { word: "अकर्तारम्", transliteration: "akartāram", meaning: "as the non-doer" },
            { word: "सः", transliteration: "saḥ", meaning: "he" },
            { word: "पश्यति", transliteration: "paśyati", meaning: "truly sees" }
          ],
          translation: "He who sees that all actions are performed by Prakriti alone, and that the Self is not the doer — he truly sees.",
          modernInterpretation: "Another 'SA PASHYATI' verse — he truly SEES. And what does he see? That ALL actions — every single one of them — are done by PRAKRITI, not by the soul. The soul is AKARTA — the non-doer. This is not laziness philosophy. This is REALITY.\n\nWho digests your food? Prakriti. Who pumps your heart? Prakriti. Who fires your neurons? Prakriti. You did not DECIDE to digest that biryani. Your stomach just did it. You did not COMMAND your heart to beat. It just beats. Even your so-called 'decisions' — choosing what to eat, where to work, whom to marry — are heavily influenced by your gunas, your conditioning, your hormones, your neural wiring. All Prakriti.\n\nSo where does that leave the SOUL? As the WITNESS. The one who watches the movie without being IN the movie. And this understanding is not meant to make you passive — it is meant to make you FREE. When you take credit for success, you also take blame for failure. When you understand you are not the doer, you lose BOTH the ego of success AND the depression of failure. You just DO what needs to be done, without the weight of 'I did this' or 'I failed at that.' That is liberation while LIVING. Not after death. RIGHT NOW."
        },
        {
          chapter: 13,
          sloka: 31,
          devanagari: "यदा भूतपृथग्भावमेकस्थमनुपश्यति ।\nतत एव च विस्तारं ब्रह्म सम्पद्यते तदा ॥३१॥",
          transliteration: "yadā bhūta-pṛthag-bhāvam eka-stham anupaśyati |\ntata eva ca vistāraṁ brahma sampadyate tadā ||31||",
          words: [
            { word: "यदा", transliteration: "yadā", meaning: "when" },
            { word: "भूत", transliteration: "bhūta", meaning: "beings" },
            { word: "पृथग्भावम्", transliteration: "pṛthag-bhāvam", meaning: "separate existence/diversity" },
            { word: "एकस्थम्", transliteration: "eka-stham", meaning: "situated in one/rooted in one" },
            { word: "अनुपश्यति", transliteration: "anupaśyati", meaning: "sees/perceives" },
            { word: "ततः", transliteration: "tataḥ", meaning: "from that" },
            { word: "एव", transliteration: "eva", meaning: "alone" },
            { word: "विस्तारम्", transliteration: "vistāram", meaning: "expansion" },
            { word: "ब्रह्म", transliteration: "brahma", meaning: "Brahman (the Absolute)" },
            { word: "सम्पद्यते", transliteration: "sampadyate", meaning: "attains/becomes" },
            { word: "तदा", transliteration: "tadā", meaning: "then" }
          ],
          translation: "When one perceives the diversity of beings as rooted in One, and their expansion as coming from that One alone, then one attains Brahman.",
          modernInterpretation: "This verse is the spiritual equivalent of seeing the UNIFIED THEORY of everything. When you look at the world, you see billions of different beings — different species, different people, different personalities. It looks like CHAOS. But Krishna says when you realize that all this diversity is rooted in ONE source and all this expansion is from that ONE — that is when you BECOME Brahman.\n\nThink of an ocean. You see millions of waves — big ones, small ones, crashing ones, calm ones. Each wave looks different, acts different, has a different lifespan. But what is EVERY wave made of? The SAME ocean. The diversity is real at one level, but the UNITY is real at a deeper level. When you see the ocean in every wave, you have understood reality.\n\nOr think of gold. You go to a jewellery shop in Zaveri Bazaar. You see rings, chains, bangles, earrings — hundreds of different forms. But a goldsmith does not see FORMS. He sees GOLD. Different shapes, same substance. That is the vision Krishna is describing. When you see the one Brahman expressing itself as the chai-wallah, the CEO, the crow, the cow, the cloud, and the cricket ball — all ONE substance in different forms — THAT is when you transcend the illusion of separation. That is when you BECOME what you always were."
        },
        {
          chapter: 13,
          sloka: 32,
          devanagari: "अनादित्वान्निर्गुणत्वात्परमात्मायमव्ययः ।\nशरीरस्थोऽपि कौन्तेय न करोति न लिप्यते ॥३२॥",
          transliteration: "anāditvān nirguṇatvāt paramātmāyam avyayaḥ |\nśarīra-stho'pi kaunteya na karoti na lipyate ||32||",
          words: [
            { word: "अनादित्वात्", transliteration: "anāditvāt", meaning: "due to being beginningless" },
            { word: "निर्गुणत्वात्", transliteration: "nirguṇatvāt", meaning: "due to being beyond the gunas" },
            { word: "परमात्मा", transliteration: "paramātmā", meaning: "the Supreme Self" },
            { word: "अयम्", transliteration: "ayam", meaning: "this" },
            { word: "अव्ययः", transliteration: "avyayaḥ", meaning: "imperishable" },
            { word: "शरीरस्थः", transliteration: "śarīra-sthaḥ", meaning: "dwelling in the body" },
            { word: "अपि", transliteration: "api", meaning: "even though" },
            { word: "कौन्तेय", transliteration: "kaunteya", meaning: "O son of Kunti" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "करोति", transliteration: "karoti", meaning: "does/acts" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "लिप्यते", transliteration: "lipyate", meaning: "is tainted/affected" }
          ],
          translation: "Being beginningless and beyond the gunas, this imperishable Supreme Self, though dwelling in the body, O son of Kunti, neither acts nor is tainted.",
          modernInterpretation: "Krishna is describing the ULTIMATE Teflon coating. The Supreme Self sits INSIDE the body but nothing STICKS to it. Na karoti — it does NOT act. Na lipyate — it is NOT tainted. Even though it is right there in the middle of all the chaos, drama, and mess of bodily existence.\n\nWhy? Two reasons. ANADITVAT — because it is beginningless. Anything with a beginning can be changed, modified, corrupted. But something that has ALWAYS existed? It has no vulnerability to change. It was never 'created' so it cannot be 'corrupted.' And NIRGUNATVAT — because it is beyond the three gunas. Sattva, rajas, tamas — these are Prakriti's paintbrushes. They colour EVERYTHING in nature. But the Supreme Self is beyond their reach. It is like trying to paint the sky — you can throw all the colour you want, the sky remains untouched.\n\nSo here you are — your body is getting tired, your mind is stressed about deadlines, your emotions are swinging like a Mumbai local — but the REAL you, the Paramatma within, is sitting there like a lotus in muddy water. Untouched. Unstained. Unbothered. The mud does not know the lotus is above it. And the lotus does not care about the mud. THAT is your true nature. Not the stress. Not the anxiety. Not the 47 unread WhatsApp messages. The untouchable, imperishable, forever-pure SELF."
        },
        {
          chapter: 13,
          sloka: 33,
          devanagari: "यथा सर्वगतं सौक्ष्म्यादाकाशं नोपलिप्यते ।\nसर्वत्रावस्थितो देहे तथात्मा नोपलिप्यते ॥३३॥",
          transliteration: "yathā sarva-gataṁ saukṣmyād ākāśaṁ nopalipyate |\nsarvatrāvasthito dehe tathātmā nopalipyate ||33||",
          words: [
            { word: "यथा", transliteration: "yathā", meaning: "just as" },
            { word: "सर्वगतम्", transliteration: "sarva-gatam", meaning: "all-pervading" },
            { word: "सौक्ष्म्यात्", transliteration: "saukṣmyāt", meaning: "due to subtlety" },
            { word: "आकाशम्", transliteration: "ākāśam", meaning: "space/ether" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "उपलिप्यते", transliteration: "upalipyate", meaning: "is tainted" },
            { word: "सर्वत्र", transliteration: "sarvatra", meaning: "everywhere" },
            { word: "अवस्थितः", transliteration: "avasthitaḥ", meaning: "situated" },
            { word: "देहे", transliteration: "dehe", meaning: "in the body" },
            { word: "तथा", transliteration: "tathā", meaning: "similarly" },
            { word: "आत्मा", transliteration: "ātmā", meaning: "the Self" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "उपलिप्यते", transliteration: "upalipyate", meaning: "is tainted" }
          ],
          translation: "Just as the all-pervading space is not tainted because of its subtlety, so the Self, though situated everywhere in the body, is not tainted.",
          modernInterpretation: "Krishna gives the PERFECT analogy. Space — aakaash — is EVERYWHERE. It is inside your room, inside a garbage dump, inside a palace, inside a sewer. But does space ever become DIRTY? Does the space inside a dustbin start smelling? No. Because space is too SUBTLE to be affected by gross things. Smoke may fill a room, but the space itself is untouched. Remove the smoke, and the space is exactly as it was.\n\nYour ATMA is like that. It is inside the body, which gets sick, which ages, which does embarrassing things, which sometimes eats too much paneer tikka at weddings. But the atma inside? UNTOUCHED. Your body commits a mistake — the atma is not stained. Your mind has negative thoughts — the atma is not corrupted. Your ego gets bruised — the atma does not even notice.\n\nThis is such a freeing realisation. We spend our ENTIRE lives thinking we are damaged, broken, sinful, not good enough. Therapy bills, self-help books, motivation seminars — all because we think something is WRONG with us. But Krishna says the REAL you — the atma — has NEVER been damaged. Not once. Not ever. You are not broken. You are space pretending to be the room. And space cannot break. You just need to remember WHAT you are. That is the whole game."
        },
        {
          chapter: 13,
          sloka: 34,
          devanagari: "यथा प्रकाशयत्येकः कृत्स्नं लोकमिमं रविः ।\nक्षेत्रं क्षेत्री तथा कृत्स्नं प्रकाशयति भारत ॥३४॥",
          transliteration: "yathā prakāśayaty ekaḥ kṛtsnaṁ lokam imaṁ raviḥ |\nkṣetraṁ kṣetrī tathā kṛtsnaṁ prakāśayati bhārata ||34||",
          words: [
            { word: "यथा", transliteration: "yathā", meaning: "just as" },
            { word: "प्रकाशयति", transliteration: "prakāśayati", meaning: "illuminates" },
            { word: "एकः", transliteration: "ekaḥ", meaning: "one" },
            { word: "कृत्स्नम्", transliteration: "kṛtsnam", meaning: "entire" },
            { word: "लोकम्", transliteration: "lokam", meaning: "world" },
            { word: "इमम्", transliteration: "imam", meaning: "this" },
            { word: "रविः", transliteration: "raviḥ", meaning: "the sun" },
            { word: "क्षेत्रम्", transliteration: "kṣetram", meaning: "the field (body)" },
            { word: "क्षेत्री", transliteration: "kṣetrī", meaning: "the knower of the field (soul)" },
            { word: "तथा", transliteration: "tathā", meaning: "similarly" },
            { word: "कृत्स्नम्", transliteration: "kṛtsnam", meaning: "entirely" },
            { word: "प्रकाशयति", transliteration: "prakāśayati", meaning: "illuminates" },
            { word: "भारत", transliteration: "bhārata", meaning: "O descendant of Bharata" }
          ],
          translation: "Just as the one sun illuminates this entire world, so the Lord of the Field (the Soul) illuminates the entire field (the body), O Bharata.",
          modernInterpretation: "What a STUNNING analogy. One sun — EKAH RAVIH — lights up the ENTIRE world. Not multiple suns for different countries. Not a separate sun for India and another for America. ONE sun. Similarly, ONE atma illuminates the ENTIRE body. Your eyes see because the atma's consciousness powers them. Your ears hear because the atma is behind them. Your brain thinks because the atma's awareness activates it. Remove the atma, and the body is a corpse — all the organs are there, all the neurons are there, but there is NO light.\n\nThis is why a dead body cannot see even though it has eyes. The hardware is intact, but the POWER SOURCE is gone. The atma was the electricity, and now the building is dark.\n\nAnd notice — the sun illuminates WITHOUT being affected by what it illuminates. The sun shines on a temple and a toilet equally. The sun does not become holy by shining on a temple or dirty by shining on a gutter. Similarly, the atma illuminates all the body's activities — good and bad — without being affected. Your body does something noble? The atma illuminates it. Your body does something shameful? The atma illuminates that too. But like the sun, it remains PURE. It is just the light source. It does not become what it illuminates."
        },
        {
          chapter: 13,
          sloka: 35,
          devanagari: "क्षेत्रक्षेत्रज्ञयोरेवमन्तरं ज्ञानचक्षुषा ।\nभूतप्रकृतिमोक्षं च ये विदुर्यान्ति ते परम् ॥३५॥",
          transliteration: "kṣetra-kṣetrajñayor evam antaraṁ jñāna-cakṣuṣā |\nbhūta-prakṛti-mokṣaṁ ca ye vidur yānti te param ||35||",
          words: [
            { word: "क्षेत्र", transliteration: "kṣetra", meaning: "the field (body)" },
            { word: "क्षेत्रज्ञयोः", transliteration: "kṣetrajñayoḥ", meaning: "and the knower of the field" },
            { word: "एवम्", transliteration: "evam", meaning: "thus" },
            { word: "अन्तरम्", transliteration: "antaram", meaning: "the difference" },
            { word: "ज्ञानचक्षुषा", transliteration: "jñāna-cakṣuṣā", meaning: "with the eye of knowledge" },
            { word: "भूत", transliteration: "bhūta", meaning: "beings" },
            { word: "प्रकृति", transliteration: "prakṛti", meaning: "material nature" },
            { word: "मोक्षम्", transliteration: "mokṣam", meaning: "liberation" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "ये", transliteration: "ye", meaning: "those who" },
            { word: "विदुः", transliteration: "viduḥ", meaning: "know" },
            { word: "यान्ति", transliteration: "yānti", meaning: "go/attain" },
            { word: "ते", transliteration: "te", meaning: "they" },
            { word: "परम्", transliteration: "param", meaning: "the Supreme" }
          ],
          translation: "Those who, with the eye of knowledge, perceive the distinction between the Field and the Knower of the Field, and the liberation of beings from material nature — they attain the Supreme.",
          modernInterpretation: "And HERE is the grand finale of Chapter 13. The ENTIRE chapter boils down to this: see the DIFFERENCE between the field and the knower of the field with the EYE OF KNOWLEDGE — jnana chakshusha — and you are FREE. You attain the PARAM — the Supreme.\n\nNotice — Krishna says the 'eye of KNOWLEDGE,' not the eye of the body. You cannot see this distinction with your physical eyes. You cannot see it through a microscope or a telescope. You need a different kind of LENS — the lens of wisdom, discrimination, and deep understanding. This is why self-inquiry matters more than self-improvement.\n\nThe whole chapter has been building to this crescendo. Verse by verse, Krishna has explained what the field is, who the knower is, what knowledge consists of, how Prakriti and Purusha interact, how the gunas trap you, and how equal vision liberates you. And now He says — those who GET IT, those who truly UNDERSTAND this distinction and thereby understand how beings can be FREE from Prakriti's grip — they reach the SUPREME goal.\n\nThis is your graduation certificate from Chapter 13. The course was 'Kshetra Kshetrajna Vibhaga Yoga.' The exam question was simple: Can you tell the DANCER from the DANCE? The SCREEN from the MOVIE? The GOLD from the ORNAMENT? If yes — congratulations. You have passed. You are heading to the PARAM. The Supreme. Game over. Or rather — game UNDERSTOOD."
        }
]
